insert into categories(name) values ('Frontend');
insert into categories(name, parent_id)values ('Angular', (select id from (select * from categories) as `c*` where name = 'Frontend'));
insert into categories(name, parent_id)values ('HTML', (select id from (select * from categories) as `c*` where name = 'Frontend'));
insert into categories(name, parent_id)values ('CSS', (select id from (select * from categories) as `c*` where name = 'Frontend'));
insert into categories(name, parent_id)values ('JavaScript', (select id from (select * from categories) as `c*` where name = 'Frontend'));
insert into categories(name, parent_id)values ('Vue', (select id from (select * from categories) as `c*` where name = 'Frontend'));
insert into categories(name, parent_id)values ('JQuery', (select id from (select * from categories) as `c*` where name = 'Frontend'));
insert into categories(name, parent_id)values ('React', (select id from (select * from categories) as `c*` where name = 'Frontend'));
insert into categories(name, parent_id)values ('TypeScript', (select id from (select * from categories) as `c*` where name = 'Frontend'));
insert into categories(name, parent_id)values ('Ember', (select id from (select * from categories) as `c*` where name = 'Frontend'));
insert into categories(name, parent_id)values ('Next.js', (select id from (select * from categories) as `c*` where name = 'Frontend'));
insert into categories(name, parent_id)values ('Elm', (select id from (select * from categories) as `c*` where name = 'Frontend'));
insert into categories(name, parent_id)values ('Svelte', (select id from (select * from categories) as `c*` where name = 'Frontend'));

insert into categories(name) values ('Backend');
insert into categories(name, parent_id)values ('PHP', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('Python', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('Ruby on Rails', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('Yii', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('Laravel', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('SQL', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('Ruby', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('Symfony', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('Java', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('Node.js', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('GO', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('Slim', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('Silex', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('Firebase', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('C#', (select id from (select * from categories) as `c*` where name = 'Backend'));
insert into categories(name, parent_id)values ('Deno', (select id from (select * from categories) as `c*` where name = 'Backend'));

insert into categories(name) values ('System programing');
insert into categories(name) values ('Marketing');
insert into categories(name) values ('Video/3D');
insert into categories(name) values ('Graphic');
insert into categories(name) values ('Tools');
insert into categories(name) values ('Mobile development');
insert into categories(name) values ('Gamedev');
insert into categories(name) values ('CMS');
insert into categories(name) values ('Blockchain');
insert into categories(name) values ('Testing/QA');
insert into categories(name) values ('Other');